---
- name: 'Configure and start unbound'
  hosts: 'all'
  gather_facts: true
  become: true

  handlers:

    - name: 'Restart the unbound service'
      ansible.builtin.service:
        name: 'unbound'
        state: 'restarted'
      when:
        - 'not unbound_service_started.changed | bool'

  tasks:

    - name: 'Create the unbound control key'
      ansible.builtin.command:
        cmd: '/usr/sbin/unbound-control-setup -d /etc/unbound/'
        creates: '/etc/unbound/unbound_control.key'

    - name: 'Start the unbound-anchor service'
      ansible.builtin.service:
        name: 'unbound-anchor.service'
        state: 'started'

    - name: 'Start the unbound service'
      ansible.builtin.service:
        name: 'unbound'
        state: 'started'
      register: unbound_service_started

    - name: 'Enable the unbound service'
      ansible.builtin.service:
        name: 'unbound'
        enabled: true
